<?php declare(strict_types = 1);

/**
 * This file is part of the FireHub Project ecosystem
 *
 * @author Danijel Galić <danijel.galic@outlook.com>
 * @copyright 2026-present The FireHub Project - All rights reserved
 * @license https://opensource.org/license/Apache-2-0 Apache License, Version 2.0
 *
 * @php-version >=8.2
 * @package Runtime
 */

namespace FireHub\Runtime;

use FireHub\Core\Boundary\Runtime\NativeRuntime;
use FireHub\Runtime\Exception\ {
    RandomByteLengthTooSmallException, RandomMaximumBelowMinimumException, RandomNumberAboveGeneratorMaximumException,
    RandomNumberBelowMinimumException, SecureRandomBytesException, SecureNumberException
};
use Random\RandomException;

use function mt_getrandmax;
use function mt_rand;
use function random_bytes;
use function random_int;

/**
 * ### PHP Runtime Random Utilities
 *
 * Provides low-level wrappers for generating pseudo-random and cryptographically secure random values using native
 * PHP random functions while preserving native runtime behavior.
 *
 * This component exposes native random number and random byte generation through a consistent FireHub Runtime API
 * without altering PHP randomness semantics.
 * @since 1.0.0
 */
final class Random extends NativeRuntime {

    /**
     * ### Generate a random value via the Mersenne Twister Random Number Generator
     * @since 1.0.0
     *
     * @param non-negative-int $min [optional] <p>
     * Optional lowest value to be returned.
     * </p>
     * @param null|non-negative-int $max [optional] <p>
     * Optional highest value to be returned.
     * </p>
     *
     * @throws \FireHub\Runtime\Exception\RandomNumberBelowMinimumException If $min is less than 0.
     * @throws \FireHub\Runtime\Exception\RandomMaximumBelowMinimumException If $max is less than $min.
     * @throws \FireHub\Runtime\Exception\RandomNumberAboveGeneratorMaximumException If $max is greater than
     * mt_getrandmax().
     *
     * @return non-negative-int A random integer value between min and max.
     */
    public static function number (int $min = 0, ?int $max = null):int {

        if ($min < 0)
            throw new RandomNumberBelowMinimumException(
                'The minimum value must be greater than or equal to zero.',
                [
                    'minimum' => 0,
                    'value' => $min,
                ]
            );

        if ($max !== null && $max < $min)
            throw new RandomMaximumBelowMinimumException(
                'The maximum value must be greater than or equal to the minimum value.',
                [
                    'minimum' => $min,
                    'maximum' => $max,
                ]
            );

        if ($max !== null && $max > $maximum = mt_getrandmax())
            throw new RandomNumberAboveGeneratorMaximumException(
                'The maximum value must be less than or equal to the maximum value supported by the generator.',
                [
                    'maximum' => $maximum,
                    'value' => $max,
                ]
            );

        return mt_rand($min, $max ?? ($maximum ?? 0));

    }

    /**
     * ### Get a cryptographically secure, uniformly selected integer
     *
     * The randomness generated by this function is suitable for all applications, including the generation of
     * long-term secrets, such as encryption keys.
     * @since 1.0.0
     *
     * @param int $min <p>
     * Optional lowest value to be returned.
     * </p>
     * @param int $max <p>
     * Optional highest value to be returned.
     * </p>
     *
     * @throws \FireHub\Runtime\Exception\RandomMaximumBelowMinimumException If $max is less than $min.
     * @throws \FireHub\Runtime\Exception\SecureNumberException If a cryptographically secure source of randomness is
     * unavailable.
     *
     * @return int A cryptographically secure, uniformly selected integer from the closed interval [min, max].<br>
     * Both min and max are possible return values.
     *
     * @caution This method is significantly slower than non-cryptographic random number generators like Random::number.
     */
    public static function secureNumber (int $min, int $max):int {

        if ($max < $min)
            throw new RandomMaximumBelowMinimumException;

        try {

            return random_int($min, $max);

        } catch (RandomException $e) {

            throw new SecureNumberException(
                'Failed to generate a cryptographically secure random number.',
                [
                    'min' => $min,
                    'max' => $max,
                ],
                previous: $e
            );

        }

    }

    /**
     * ### Get cryptographically secure random bytes
     *
     * Generates a string containing uniformly selected random bytes with the requested length.
     *
     * As the returned bytes are selected completely randomly, the resulting string is likely to contain unprintable
     * characters or invalid UTF-8 sequences. It may be necessary to encode it before transmission or display.
     *
     * The randomness generated by this function is suitable for all applications, including the generation of
     * long-term secrets, such as encryption keys.
     * @since 1.0.0
     *
     * @param positive-int $length <p>
     * The length of the random string that should be returned in bytes; must be 1 or greater.
     * </p>
     *
     * @throws \FireHub\Runtime\Exception\RandomByteLengthTooSmallException If the length is less than 1.
     * @throws \FireHub\Runtime\Exception\SecureRandomBytesException If a cryptographically secure source of randomness
     * is unavailable.
     *
     * @return non-empty-string A string containing the requested number of cryptographically secure random bytes.
     */
    public static function bytes (int $length):string {

        if ($length < 1)
            throw new RandomByteLengthTooSmallException(
                'The length of the random string must be greater than zero.',
                [
                    'length' => $length,
                    'minimum' => 1,
                ]
            );

        try {

            return random_bytes($length);

        } catch (RandomException $e) {

            throw new SecureRandomBytesException(
                'Failed to generate a cryptographically secure random string.',
                [
                    'length' => $length,
                ],
                previous: $e
            );

        }

    }

}